# Generated by Django 5.0.6 on 2025-09-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('short_description', models.TextField(max_length=300, verbose_name='الوصف المختصر')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('planning', 'تخطيط'), ('active', 'نشط'), ('completed', 'مكتمل'), ('paused', 'متوقف مؤقتاً'), ('cancelled', 'ملغى')], default='planning', max_length=20, verbose_name='الحالة')),
                ('progress', models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='نسبة الإنجاز')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('allow_participation', models.BooleanField(default=True, verbose_name='السماح بالمشاركة')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاركين')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('external_link', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد التواصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('message', models.TextField(blank=True, verbose_name='رسالة')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'unique_together': {('project', 'email')},
            },
        ),
    ]
