# Generated by Django 5.0.6 on 2025-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('banner', 'بانر'), ('text', 'نص'), ('html', 'HTML')], default='banner', max_length=20, verbose_name='النوع')),
                ('placement', models.CharField(choices=[('header', 'الرأس'), ('sidebar', 'الشريط الجانبي'), ('footer', 'التذييل'), ('content_top', 'أعلى المحتوى'), ('content_bottom', 'أسفل المحتوى'), ('between_posts', 'بين المنشورات')], max_length=20, verbose_name='الموضع')),
                ('image', models.ImageField(blank=True, upload_to='ads/', verbose_name='الصورة')),
                ('text_content', models.TextField(blank=True, verbose_name='المحتوى النصي')),
                ('html_content', models.TextField(blank=True, verbose_name='محتوى HTML')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط الإعلان')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='نص الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='عدد النقرات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['placement', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='الصورة')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان Meta')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='وصف Meta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('is_replied', models.BooleanField(default=False, verbose_name='تم الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
            ],
            options={
                'verbose_name': 'مشترك النشرة',
                'verbose_name_plural': 'مشتركو النشرة',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='منصة المحتوى المتعدد الوسائط', max_length=200, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف الموقع')),
                ('site_logo', models.ImageField(blank=True, upload_to='site/', verbose_name='شعار الموقع')),
                ('site_favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='أيقونة الموقع')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الاتصال')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف الاتصال')),
                ('contact_whatsapp', models.CharField(default='0097335370499', max_length=20, verbose_name='واتساب')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان Meta')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='وصف Meta')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='كلمات مفتاحية')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/alibasheerahmed2', verbose_name='فيسبوك')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/alibasheer09', verbose_name='تويتر')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@alibasheer', verbose_name='يوتيوب')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/alibasheerahmed2', verbose_name='انستجرام')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/alibasheerahmed', verbose_name='تيليجرام')),
                ('soundcloud_url', models.URLField(blank=True, default='https://soundcloud.com/alibasheerahmed2', verbose_name='ساوندكلاود')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com/@alibasheerahmed2', verbose_name='تيك توك')),
                ('youtube_api_key', models.CharField(blank=True, max_length=100, verbose_name='مفتاح YouTube API')),
                ('soundcloud_client_id', models.CharField(blank=True, max_length=100, verbose_name='معرف SoundCloud')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=100, verbose_name='رمز Telegram Bot')),
                ('newsletter_enabled', models.BooleanField(default=True, verbose_name='تفعيل النشرة الإخبارية')),
                ('newsletter_from_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد النشرة')),
                ('rss_enabled', models.BooleanField(default=True, verbose_name='تفعيل RSS')),
                ('rss_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان RSS')),
                ('rss_description', models.TextField(blank=True, verbose_name='وصف RSS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
