# Generated by Django 5.0.6 on 2025-09-21 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة شخصية')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الشخصي')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='الموقع')),
                ('show_email', models.BooleanField(default=False, verbose_name='إظهار البريد الإلكتروني')),
                ('allow_messages', models.BooleanField(default=True, verbose_name='السماح بالرسائل')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='الاشتراك في النشرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
