# Generated by Django 5.0.6 on 2025-09-21 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='المقطع')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/images/', verbose_name='الصورة المميزة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='السماح بالتعليقات')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان Meta')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='وصف Meta')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='كلمات مفتاحية')),
                ('tags', models.CharField(blank=True, help_text='افصل بفواصل', max_length=200, verbose_name='العلامات')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('categories', models.ManyToManyField(blank=True, to='core.category', verbose_name='التصنيفات')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
